In [26]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

1.3.5
1.21.6

In [27]:
n_rows = 5
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1 ,10, size=(n_rows, n_cols)), columns=cols)

df

   A  B  C  D  E
0  6  3  4  5  8
1  1  4  6  3  4
2  1  1  3  6  7
3  1  3  7  5  6
4  6  8  1  3  5

In [28]:
#Mengganti nama label untuk sebuah kolom pada data frame

df.rename(columns={'C':'Hobi'})

   A  B  Hobi  D  E
0  6  3     4  5  8
1  1  4     6  3  4
2  1  1     3  6  7
3  1  3     7  5  6
4  6  8     1  3  5

In [29]:
#Mengganti nama label untuk banyak kolom pada data frame

df.rename(columns={'A':'Nama', 'B':'Alamat', 'D':'Kota'})

   Nama  Alamat  C  Kota  E
0     6       3  4     5  8
1     1       4  6     3  4
2     1       1  3     6  7
3     1       3  7     5  6
4     6       8  1     3  5

**07 Menghapus (Drop) missing values (NaN)**

In [30]:
df = pd.util.testing.makeMissingDataframe().reset_index()
df.head()

        index         A         B         C         D
0  9EzHqe6eM4  0.607781 -0.618403  0.789731  0.119868
1  UplP5dBbGf -0.235849  0.717634  2.915247 -0.186418
2  XkD7hGgOTi -2.137024       NaN -0.089335  0.105113
3  HD7X19nvvm       NaN  1.134879  0.431393 -0.548587
4  uNJUGN6CjB -1.577995  1.772372  0.912821  0.846976

In [31]:
df = df.rename(columns={'index':'Z'})
df.head()

            Z         A         B         C         D
0  9EzHqe6eM4  0.607781 -0.618403  0.789731  0.119868
1  UplP5dBbGf -0.235849  0.717634  2.915247 -0.186418
2  XkD7hGgOTi -2.137024       NaN -0.089335  0.105113
3  HD7X19nvvm       NaN  1.134879  0.431393 -0.548587
4  uNJUGN6CjB -1.577995  1.772372  0.912821  0.846976

In [32]:
df_backup = df.copy(deep=True)

In [33]:
#menghapus (drop) setiap kolom yang mengandung missing values
df = df.dropna(axis='columns')
df.head()

            Z
0  9EzHqe6eM4
1  UplP5dBbGf
2  XkD7hGgOTi
3  HD7X19nvvm
4  uNJUGN6CjB

In [34]:
df = df_backup.copy(deep=True)
df = df.dropna(axis='rows')
df.head()

            Z         A         B         C         D
0  9EzHqe6eM4  0.607781 -0.618403  0.789731  0.119868
1  UplP5dBbGf -0.235849  0.717634  2.915247 -0.186418
4  uNJUGN6CjB -1.577995  1.772372  0.912821  0.846976
6  Puxsig0Q4n  1.708682 -0.035233  0.504973  0.718937
7  MUfytwZ5mw -1.087894  1.912789 -0.383310  2.072812

In [35]:
#Presentase missing values untuk tiap kolom
df = df_backup.copy(deep=True)
df.isna().mean()

Z    0.000000
A    0.100000
B    0.066667
C    0.066667
D    0.166667
dtype: float64

In [37]:
#Menghapus (drop) setiap kolom yang mengandung missing values berdasarkan threshold
treshold = len(df) * 0.9
df = df.dropna(thresh=treshold, axis='columns')
df.head()

            Z         A         B         C
0  9EzHqe6eM4  0.607781 -0.618403  0.789731
1  UplP5dBbGf -0.235849  0.717634  2.915247
2  XkD7hGgOTi -2.137024       NaN -0.089335
3  HD7X19nvvm       NaN  1.134879  0.431393
4  uNJUGN6CjB -1.577995  1.772372  0.912821